"""1

Revision ID: 370dbc05a0f5
Revises: 
Create Date: 2021-04-09 22:07:41.545515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370dbc05a0f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default_role_name', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default_role_name'), 'roles', ['default_role_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('nomor', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_nomor'), 'users', ['nomor'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('date_upload', sa.DateTime(), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('dosen1', sa.String(length=128), nullable=True),
    sa.Column('dosen1_sign', sa.Boolean(), nullable=False),
    sa.Column('dosen2', sa.String(length=128), nullable=True),
    sa.Column('dosen2_sign', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_date_upload'), 'files', ['date_upload'], unique=False)
    op.create_table('file_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('sign1', sa.String(length=128), nullable=True),
    sa.Column('sign2', sa.String(length=128), nullable=True),
    sa.Column('sign3', sa.String(length=128), nullable=True),
    sa.Column('sign1_date', sa.DateTime(), nullable=True),
    sa.Column('sign2_date', sa.DateTime(), nullable=True),
    sa.Column('sign3_date', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_signs_date'), 'file_signs', ['date'], unique=False)
    op.create_index(op.f('ix_file_signs_sign1_date'), 'file_signs', ['sign1_date'], unique=False)
    op.create_index(op.f('ix_file_signs_sign2_date'), 'file_signs', ['sign2_date'], unique=False)
    op.create_index(op.f('ix_file_signs_sign3_date'), 'file_signs', ['sign3_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_signs_sign3_date'), table_name='file_signs')
    op.drop_index(op.f('ix_file_signs_sign2_date'), table_name='file_signs')
    op.drop_index(op.f('ix_file_signs_sign1_date'), table_name='file_signs')
    op.drop_index(op.f('ix_file_signs_date'), table_name='file_signs')
    op.drop_table('file_signs')
    op.drop_index(op.f('ix_files_date_upload'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_users_nomor'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_default_role_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
